# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UsersService/users_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UsersService/users_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n UsersService/users_service.proto\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"`\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\r\n\x05\x61\x64min\x18\x05 \x01(\x08\"B\n\x10ResponseWithUser\x12\x19\n\x06status\x18\x01 \x01(\x0b\x32\t.Response\x12\x13\n\x04user\x18\x02 \x01(\x0b\x32\x05.User2\xed\x01\n\x08UsersAPI\x12\x1d\n\x07IsExist\x12\x05.User\x1a\t.Response\"\x00\x12$\n\x06\x43reate\x12\x05.User\x1a\x11.ResponseWithUser\"\x00\x12$\n\x06Verify\x12\x05.User\x1a\x11.ResponseWithUser\"\x00\x12\"\n\x04Info\x12\x05.User\x1a\x11.ResponseWithUser\"\x00\x12,\n\x0eUpdateUserData\x12\x05.User\x1a\x11.ResponseWithUser\"\x00\x12$\n\x0eUpdatePassword\x12\x05.User\x1a\t.Response\"\x00\x62\x06proto3'
)




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Response.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=77,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='User.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='User.first_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='User.last_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='admin', full_name='User.admin', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=175,
)


_RESPONSEWITHUSER = _descriptor.Descriptor(
  name='ResponseWithUser',
  full_name='ResponseWithUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ResponseWithUser.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='ResponseWithUser.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=243,
)

_RESPONSEWITHUSER.fields_by_name['status'].message_type = _RESPONSE
_RESPONSEWITHUSER.fields_by_name['user'].message_type = _USER
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['ResponseWithUser'] = _RESPONSEWITHUSER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'UsersService.users_service_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'UsersService.users_service_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

ResponseWithUser = _reflection.GeneratedProtocolMessageType('ResponseWithUser', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEWITHUSER,
  '__module__' : 'UsersService.users_service_pb2'
  # @@protoc_insertion_point(class_scope:ResponseWithUser)
  })
_sym_db.RegisterMessage(ResponseWithUser)



_USERSAPI = _descriptor.ServiceDescriptor(
  name='UsersAPI',
  full_name='UsersAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=246,
  serialized_end=483,
  methods=[
  _descriptor.MethodDescriptor(
    name='IsExist',
    full_name='UsersAPI.IsExist',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='UsersAPI.Create',
    index=1,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSEWITHUSER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Verify',
    full_name='UsersAPI.Verify',
    index=2,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSEWITHUSER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Info',
    full_name='UsersAPI.Info',
    index=3,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSEWITHUSER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateUserData',
    full_name='UsersAPI.UpdateUserData',
    index=4,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSEWITHUSER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdatePassword',
    full_name='UsersAPI.UpdatePassword',
    index=5,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSAPI)

DESCRIPTOR.services_by_name['UsersAPI'] = _USERSAPI

# @@protoc_insertion_point(module_scope)
